# Generated by Django 4.2.1 on 2023-08-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('verification_code', models.CharField(blank=True, max_length=4, null=True)),
                ('invite_code', models.CharField(blank=True, max_length=6, null=True)),
                ('authorized', models.BooleanField(default=False)),
                ('entered_invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_invite', to='Tele_API.userprofile')),
            ],
        ),
    ]
