# Generated by Django 4.2.1 on 2023-08-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tele_API', '0002_userprofile_invite_code_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='entered_invite',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
